version: '2'
services:
  db:
    image: library/mariadb:10.1.29
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: departure_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
